# Generated by Django 5.2.7 on 2025-10-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="URL text. Example: 'fed-rate-outlook-2025'", unique=True)),
                ('category', models.CharField(choices=[('finance', 'Finance'), ('technology', 'Technology'), ('real_estate', 'Real Estate')], max_length=20)),
                ('summary', models.TextField(blank=True, help_text='Short teaser or preview paragraph')),
                ('body', models.TextField(help_text='Full article content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
