# Generated by Django 5.2.7 on 2025-10-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_comment_newsletter_sponsor_sponsoredcontent_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='website_art_created_20a7fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='website_art_status_f5d771_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='website_art_categor_0d9117_idx',
        ),
    ]
