# Generated by Django 5.2.7 on 2025-11-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_article_website_art_created_20a7fe_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('finance', 'Finance'), ('technology', 'Technology'), ('real_estate', 'Real Estate'), ('trade', 'Trade')], max_length=20),
        ),
    ]
