"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env()
# read_env() with no path does frame-inspection to guess the .env location
# based on the caller's file (this file, core/settings.py), which means it
# looks in core/.env - not the project root, where every deploy/runbook
# actually expects .env to live. Pass the path explicitly instead of
# relying on that.
environ.Env.read_env(str(BASE_DIR / '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', default='django-insecure-8p=l77sqg(z#49dv17pzg-+cj^e849eavvc7&1qf*e=va1@nlx')

# SECURITY WARNING: don't run with debug turned on in production!
# Use environment variable for DEBUG. Default to True for local development convenience.
# Set DJANGO_DEBUG=False in production env to disable debug mode.
DEBUG = env.bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=[
    "127.0.0.1",
    "localhost",
    "fintechrp.com",
    "www.fintechrp.com",
    "13.62.64.45",  # EC2 IP for direct access
    "fintechrp-dynamic-content-alb-263608934.eu-north-1.elb.amazonaws.com",  # ALB for health checks
    # Note: Removed wildcard patterns for better security per AWS recommendations
    # CloudFront/ALB will use X-Forwarded-Host header instead
])

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'django-error.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

SECURE_SSL_REDIRECT = False if DEBUG else True
# Trust X-Forwarded headers from ALB/CloudFront for HTTPS and Host detection
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True  # Use X-Forwarded-Host header from ALB for correct domain
USE_X_FORWARDED_PORT = True  # Use X-Forwarded-Port header from ALB
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = False if DEBUG else True
SECURE_HSTS_PRELOAD = False if DEBUG else True
SESSION_COOKIE_SECURE = False if DEBUG else True
CSRF_COOKIE_SECURE = False if DEBUG else True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'

# Admin Security Settings
# NOTE: nginx's own `allow 84.74.115.21; deny all;` on /control-panel-72d3/
# is NOT effectively restricting anything in practice - every request
# arrives at nginx from the ALB's internal IP (which matches the allowed
# 172.31.0.0/16 range), not the real visitor's IP, so nginx's allow list
# for that specific IP is never actually consulted - the admin login page
# has been reachable by anyone on the internet. AdminIPRestrictionMiddleware
# below reads the real client IP from X-Forwarded-For instead, which ALB
# does set correctly. 84.74.115.21 (the old nginx-configured IP) was
# confirmed stale; 213.55.218.85 is the current real IP as of 2026-09-15.
ADMIN_ALLOWED_IPS = env.list('ADMIN_ALLOWED_IPS', default=['127.0.0.1', '213.55.218.85'])
ADMIN_URL = 'control-panel-72d3/'
ADMIN_HONEYPOT = False  # Enable admin honeypot protection

# Google Analytics
GOOGLE_ANALYTICS_ID = 'G-5CVML1HFYR'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',

    # Third party apps
    'taggit',
    'crispy_forms',
    'crispy_bootstrap5',
    'ckeditor',
    'ckeditor_uploader',
    'robots',

    # Our apps
    'website',
]

# Site ID for django.contrib.sites
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Fix duplicate Host headers from CloudFront/ALB before any other middleware processes them
    'core.middleware.FixDuplicateHostHeaderMiddleware',
    # Restrict access to admin URL to configured IPs (nginx's own
    # restriction on this path doesn't work - see ADMIN_ALLOWED_IPS above)
    'core.middleware.AdminIPRestrictionMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Tell any well-behaved cache (browser or CDN) never to store these
    # dynamic, per-session responses. CloudFront was observed caching
    # /articles/ and serving that same cached copy for every ?q= search
    # variation, since its cache policy ignores query strings entirely -
    # this doesn't change that cache policy (needs an AWS console fix),
    # but it's the correct signal from the origin regardless.
    'core.middleware.NoStoreCacheMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # site-wide context processors from the website app
                'website.context_processors.site_settings',
                'website.context_processors.categories',
                'website.context_processors.popular_tags',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# nginx serves everything under /static/ with a 30-day immutable cache
# (nginx_alb_cloudfront.conf). Without content-hashed filenames, a
# browser that already cached e.g. main.js keeps running that stale
# copy for a month even after a new deploy - which is exactly what
# happened with the dark mode toggle: new HTML with the button, old
# cached JS with no click handler for it, so clicking did nothing.
# ManifestStaticFilesStorage renames each file to include a hash of
# its content (main.<hash>.js) and rewrites every {% static %} tag to
# match, so a changed file gets a new URL and is never served from a
# stale cache.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}

# NOTE: must have a leading slash - a bare 'media/' makes every
# ImageField.url relative to the CURRENT page instead of site-root,
# so an image referenced from e.g. /article/some-slug/ would resolve
# to /article/some-slug/media/... (wrong) instead of /media/...
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Django Compressor settings
COMPRESS_ENABLED = True
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.rCSSMinFilter',
]
COMPRESS_JS_FILTERS = ['compressor.filters.jsmin.JSMinFilter']
COMPRESS_STORAGE = 'compressor.storage.GzipCompressorFileStorage'

# CKEditor
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

# To mitigate django-ckeditor bundled CKEditor 4.x warning, prefer serving a
# maintained CKEditor build (4.25.1-lts secure version) from local static files.
# This does not change the installed package but ensures the editor loaded at runtime
# is the latest secure LTS release. Ensure the full CKEditor distribution is available
# under static/ckeditor/ckeditor/ (the deploy script handles this automatically).
CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': BASE_DIR / 'django_cache',
    }
}

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_SECURE = False if DEBUG else True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
# Gmail SMTP requires (or silently rewrites) the From address to match
# the authenticated account, so this needs to be the same mailbox as
# EMAIL_HOST_USER, not an arbitrary noreply@ alias that isn't actually
# configured as a Workspace send-as address.
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='webmaster@fintechrp.com')

# Authentication settings
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Login URL for admin interface
LOGIN_URL = 'admin:login'

# Custom settings
ARTICLES_PER_PAGE = 10
PREMIUM_SUBSCRIPTION_PRICE = 9.99  # monthly subscription price

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
